import {markerShape,populationRadius,markerLegend} from './city-markers.js';
import {installRankings} from './rankings.js';
import {applyPresetUpdate} from './preset-updates.js';
import {formatCharacterLinks,parseCharacterLinks,characterLinksMarkup} from './character-links.js';
import {schema,validate} from './model.js';
const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),num=v=>v==null?'未设定':Number(v).toLocaleString('zh-CN');
let data,selected='song',mode='countries',editing=null,zoom=d3.zoomIdentity;
const svg=d3.select('#map'),group=svg.append('g'),projection=d3.geoRobinson().rotate([-11,0]).fitExtent([[20,38],[980,520]],{type:'Sphere'}),path=d3.geoPath(projection);
group.append('path').attr('d',path({type:'Sphere'})).attr('fill','#c4dce8');const lands=group.append('g'),dots=group.append('g'),rings=group.append('g').attr('pointer-events','none'),labels=group.append('g');
svg.call(d3.zoom().scaleExtent([1,40]).on('zoom',e=>{zoom=e.transform;group.attr('transform',zoom);drawCities();}));
$('#reset').onclick=()=>svg.transition().duration(250).call(d3.zoom().transform,d3.zoomIdentity);
const status=text=>$('#status').textContent=text;
const owner=id=>data.countries.find(c=>c.id===id);
function displayNotes(s){return (s||'').split(/(?<=[。！？])/).filter(t=>!/(色块提取|待核|未命名地区的组织|原图范围内|以用户最新|轮廓与归属仍可编辑)/.test(t)).join('');}
function choose(id){selected=id;renderList();renderDetails();paint();}
function renderList(){const q=$('#search').value.trim().toLowerCase(),rows=data[mode].filter(c=>[c.name,c.englishName,c.localName,c.realName,c.notes,...(c.searchAliases||[])].join(' ').toLowerCase().includes(q));$('#countriesTab').textContent=`国家 / 地区 ${data.countries.length}`;$('#citiesTab').textContent=`城市 ${data.cities.length}`;$('#countriesTab').classList.toggle('active',mode==='countries');$('#citiesTab').classList.toggle('active',mode==='cities');$('#list').innerHTML=rows.map(c=>`<button class="row ${c.id===selected?'active':''}" data-id="${esc(c.id)}">${esc(c.name)}<small>${esc(c.englishName||c.alias||'')}</small></button>`).join('')||'<p>没有匹配记录</p>';$('#list').querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>choose(b.dataset.id));}
function renderDetails(){const city=data.cities.find(c=>c.id===selected),e=city||owner(selected);if(!e)return;const native=[{name:e.localName,language:e.localLanguage},...(e.nativeNames||[])].filter(n=>n.name),children=city?[]:data.cities.filter(c=>c.countryId===e.id);
 $('#details').innerHTML=`<div class="detail-head"><div><p class="muted">${city?esc(owner(city.countryId)?.name):e.parentId?'属地 · '+esc(owner(e.parentId)?.name):'国家 / 地区'}</p><h1>${esc(e.name)}</h1><div class="subtitle">${esc(e.englishName||e.alias)}</div>${native.map(n=>`<div class="native" dir="auto">${esc(n.name)} <small class="muted">${esc(n.language)}</small></div>`).join('')}${e.fullName?`<p>${esc(e.fullName)}</p>`:''}</div><button id="edit">编辑</button></div><div class="chips">${e.featured?'<span>★ 作品重要地点</span>':''}${city?.capital?'<span>'+esc(city.capitalRole==='regional'?'地区首府':'国家首都')+'</span>':''}${e.polityType==='free-city'?'<span>自由市</span>':''}${city?.includeInNationalTotals===false?'<span>不计入国家汇总</span>':''}</div><div class="stats"><div><small>人口 · 人</small><strong>${num(e.population)}</strong></div><div><small>GDP · 亿美元</small><strong>${num(e.gdpHundredMillionUSD)}</strong></div><div><small>${city?'经度 / 纬度':'首都 / 首府'}</small><strong>${city?e.coordinates.map(n=>n.toFixed(3)).join(' / '):esc(e.capital||'未设定')}</strong></div></div>${e.realName?`<p class="muted">现实对应 / 原型：${esc(e.realName)}</p>`:''}${city?`<details ${e.relatedCharacters?.length?'open':''}><summary>关联角色 · ${e.relatedCharacters?.length||0}</summary>${characterLinksMarkup(e.relatedCharacters||[])}</details>`:''}${e.nameEtymology?`<p class="muted">名称由来：${esc(e.nameEtymology)}</p>`:''}<div class="notes">${esc(displayNotes(e.notes))||'暂无补充设定。'}</div>${city?'':`<h3>所属城市 · ${children.length}</h3><div class="city-grid">${children.map(c=>`<button data-city="${esc(c.id)}">${c.capital?'◎ ':''}${esc(c.name)}<small>${esc(c.englishName)}</small></button>`).join('')}</div>`}<details><summary>资料口径与来源</summary><p>${esc(e.demographics?.kind||'原有设定资料')}</p><p>${esc(e.demographics?.method||'')}</p><p>${esc(e.nameSource||e.source||'')}</p><p>人口与经济预设含创作估算；现实原型不等同于小说内名称或主权归属。</p></details>`;
 $('#edit').onclick=()=>edit(e,!!city);$('#details').querySelectorAll('[data-city]').forEach(b=>b.onclick=()=>choose(b.dataset.city));
}
function geo(f){const c=structuredClone(f);const polys=c.geometry.type==='Polygon'?[c.geometry.coordinates]:c.geometry.coordinates;for(const rings of polys)if(d3.geoArea({type:'Polygon',coordinates:rings})>Math.PI*2)for(const ring of rings)ring.reverse();return c;}
function draw(){const features=data.boundaries.features.map(geo);lands.selectAll('path').data(features).join('path').attr('class','geo').attr('d',path).attr('stroke','#7f98a8').attr('stroke-width',.6).attr('vector-effect','non-scaling-stroke').on('click',(e,f)=>{e.stopPropagation();choose(f.properties.id);});paint();}
function paint(){const city=data.cities.find(c=>c.id===selected),id=city?.countryId||selected;lands.selectAll('path').attr('fill',f=>{const c=owner(f.properties.id);return /^#[0-9a-f]{6}$/i.test(c?.color)?c.color:'#a4bdcb';}).attr('fill-opacity',f=>f.properties.id===id?1:.64).attr('stroke-width',f=>f.properties.id===id?1.8:.6);drawCities();}
function drawCities(){if(!data)return;const rows=data.cities.filter(c=>c.id===selected||c.capital||c.labelPriority&&zoom.k>2||zoom.k>3&&(c.population||0)>300000||zoom.k>8);const radius=c=>populationRadius(c)*Math.max(.55,Math.min(1,zoom.k/3.5));const shape=c=>markerShape(c,radius(c),{simplified:zoom.k<2&&c.id!==selected});const color=c=>shape(c).kind==='national'?'#ce4448':'#314d64';dots.selectAll('circle.city-dot').data(rows,c=>c.id).join('circle').attr('class','city-dot').attr('cx',c=>projection(c.coordinates)[0]).attr('cy',c=>projection(c.coordinates)[1]).attr('r',c=>shape(c).outerRadius/zoom.k).attr('fill','transparent').attr('stroke','none').on('click',(e,c)=>{e.stopPropagation();choose(c.id);});const marks=rows.flatMap(c=>{const m=shape(c);return [...(m.filled?[{c,r:radius(c),filled:true}]:[]),...m.rings.map((r,i)=>({c,r,filled:false,lineWidth:m.ringWidths[i]}))];});rings.selectAll('circle').data(marks,d=>d.c.id+'-'+d.filled+'-'+d.r).join('circle').attr('cx',d=>projection(d.c.coordinates)[0]).attr('cy',d=>projection(d.c.coordinates)[1]).attr('r',d=>d.r/zoom.k).attr('fill',d=>d.filled?color(d.c):'none').attr('stroke',d=>d.filled?'none':color(d.c)).attr('stroke-width',d=>(d.lineWidth||1)/zoom.k);const boxes=[];const named=$('#names').checked?[...rows].sort((a,b)=>(b.id===selected?1000:0)+(b.labelPriority||0)-(a.id===selected?1000:0)-(a.labelPriority||0)||(b.population||0)-(a.population||0)).filter(c=>{if(c.id!==selected&&zoom.k<=2.5)return false;const p=projection(c.coordinates),x=p[0]*zoom.k+10,y=p[1]*zoom.k,w=c.name.length*12+($('#stars').checked&&c.featured?18:0)+8;const box=[x,y-10,x+w,y+6];if(c.id!==selected&&boxes.some(b=>box[0]<b[2]&&box[2]>b[0]&&box[1]<b[3]&&box[3]>b[1]))return false;boxes.push(box);return true;}):[];labels.selectAll('text').data(named,c=>c.id).join('text').attr('class','map-label').attr('x',c=>projection(c.coordinates)[0]+10/zoom.k).attr('y',c=>projection(c.coordinates)[1]+3/zoom.k).attr('font-size',12/zoom.k).attr('stroke-width',3/zoom.k).text(c=>($('#stars').checked&&c.featured?'★ ':'')+c.name);}
async function persist(){try{const db=await database();await new Promise((resolve,reject)=>{const t=db.transaction('project','readwrite');t.objectStore('project').put(data,'draft');t.oncomplete=resolve;t.onerror=()=>reject(t.error);});status('已保存到此浏览器 · 下载 JSON 可备份或交给 AI');}catch{status('浏览器存储不可用，请下载 JSON 保存');}}
function database(){return new Promise((resolve,reject)=>{const r=indexedDB.open('stellagram-worldbuilding-lite',1);r.onupgradeneeded=()=>r.result.createObjectStore('project');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
async function loadDraft(){try{const db=await database();return await new Promise((resolve,reject)=>{const r=db.transaction('project').objectStore('project').get('draft');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}catch{return null;}}
function edit(e,city){editing={entity:e,city,isNew:!data.cities.includes(e)&&!data.countries.includes(e)};const f=$('#editForm');f.reset();for(const k of ['name','englishName','localName','localLanguage','population','gdpHundredMillionUSD','realName','notes'])f.elements[k].value=e[k]??'';f.elements.featured.checked=!!e.featured;f.elements.relatedCharacters.value=formatCharacterLinks(e.relatedCharacters||[]);for(const id of ['ownerField','lonField','latField','charactersField','markerField'])$('#'+id).hidden=!city;f.elements.countryId.innerHTML=data.countries.map(c=>`<option value="${esc(c.id)}">${esc(c.name)}</option>`).join('');if(city){f.elements.markerKind.value=markerShape(e,3).kind;f.elements.countryId.value=e.countryId;f.elements.lon.value=e.coordinates[0];f.elements.lat.value=e.coordinates[1];}$('#deleteCity').hidden=!city||editing.isNew;$('#editor').showModal();}
$('#editForm').onsubmit=async event=>{event.preventDefault();const form=new FormData(event.target),next=structuredClone(data),e=structuredClone(editing.entity);for(const k of ['name','englishName','localName','localLanguage','realName','notes'])e[k]=form.get(k).trim();for(const k of ['population','gdpHundredMillionUSD'])e[k]=form.get(k)===''?null:Number(form.get(k));e.featured=form.has('featured');if(editing.city){const kind=form.get('markerKind');e.capital=kind==='national'||kind==='regional';e.capitalRole=kind==='regional'?'regional':'national';e.settlementType=kind==='town'?'town':'city';try{e.relatedCharacters=parseCharacterLinks(form.get('relatedCharacters')||'');}catch(error){alert(error.message);return;}e.countryId=form.get('countryId');e.coordinates=[Number(form.get('lon')),Number(form.get('lat'))];}const list=editing.city?next.cities:next.countries,index=list.findIndex(c=>c.id===e.id);if(index<0)list.push(e);else list[index]=e;if(editing.city)for(const country of next.countries)if(country.capitalId===e.id)country.capital=e.name;try{validate(next);data=next;selected=e.id;$('#editor').close();renderList();renderDetails();paint();await persist();}catch(error){alert(error.message);}};
$('#closeEditor').onclick=()=>$('#editor').close();$('#deleteCity').onclick=async()=>{if(!confirm('删除这座城市？可从下载的 JSON 备份恢复。'))return;data.cities=data.cities.filter(c=>c.id!==editing.entity.id);for(const country of data.countries)if(country.capitalId===editing.entity.id){country.capitalId=null;country.capital='';}selected=editing.entity.countryId;$('#editor').close();renderList();renderDetails();paint();await persist();};
$('#addCity').onclick=()=>edit({id:'city-'+crypto.randomUUID(),name:'新城市',countryId:owner(selected)?.id||data.cities.find(c=>c.id===selected)?.countryId||data.countries[0].id,coordinates:[0,0],includeInNationalTotals:true},true);
$('#search').oninput=()=>data&&renderList();$('#countriesTab').onclick=()=>{mode='countries';if(data)renderList();};$('#citiesTab').onclick=()=>{mode='cities';if(data)renderList();};$('.marker-key').innerHTML=markerLegend().replace(' · 钴蓝表示海侵城市','');$('#names').onchange=drawCities;$('#stars').onchange=drawCities;$('#mapToggle').onclick=()=>{$('#mapWrap').hidden=!$('#mapWrap').hidden;$('#mapToggle').textContent=$('#mapWrap').hidden?'显示地图':'收起地图';};
$('#exportBtn').onclick=()=>{const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='随星录-世界观设定精简版.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);};$('#importBtn').onclick=()=>$('#file').click();$('#file').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>20*1024*1024)throw Error('精简设定 JSON 请控制在 20 MB 内');const next=validate(JSON.parse(await file.text()));if(!next.boundaries)next.boundaries=data.boundaries;validate(next);data=next;selected=data.countries[0].id;draw();renderList();renderDetails();await persist();}catch(error){alert(error.message);}finally{e.target.value='';}};
installRankings($('#rankingsBtn'),()=>data,choose);
try{const saved=await loadDraft();if(saved)data=validate(saved);else{const [countries,cities,boundaries,manifest]=await Promise.all(['countries.json','cities.json','boundaries.geojson','manifest.json'].map(async p=>{const r=await fetch('data/'+p);if(!r.ok)throw Error('设定文件读取失败');return r.json();}));data=validate({schema,countries,cities,boundaries,setting:manifest.setting,sourceCommit:manifest.sourceCommit});}if(saved&&!data.appliedUpdates?.includes('europe-polar-r24')){const response=await fetch('data/updates-r24.json');if(!response.ok)throw Error('设定更新暂未加载，请刷新重试');const next=structuredClone(data);if(applyPresetUpdate(next,await response.json())){data=validate(next);await persist();}}if(saved&&!data.appliedUpdates?.includes('story-links-r25')){const response=await fetch('data/updates-r25.json');if(!response.ok)throw Error('设定更新暂未加载，请刷新重试');const next=structuredClone(data);if(applyPresetUpdate(next,await response.json())){data=validate(next);await persist();}}if(!owner(selected))selected=data.countries[0].id;draw();renderList();renderDetails();$('#exportBtn').disabled=false;$('#rankingsBtn').disabled=false;$('#addCity').disabled=false;status(`${data.countries.length} 个国家与地区 · ${data.cities.length} 座城市 · 无配图 / 无高程`);}catch(error){status('加载失败：'+error.message);$('#list').textContent='请刷新或通过本地 HTTP 服务打开';}


