export const schema='stellagram-worldbuilding-lite-v1';
export function validate(p){
 if(p.schema!==schema||!Array.isArray(p.countries)||!Array.isArray(p.cities)||p.countries.length===0||p.countries.length>1000||p.cities.length>20000)throw Error('请选择本精简版导出的设定 JSON');
 const ids=new Set();for(const x of [...p.countries,...p.cities]){if(!x||typeof x.id!=='string'||!x.id||ids.has(x.id)||typeof x.name!=='string'||!x.name.trim())throw Error('名称或 ID 无效');ids.add(x.id);for(const k of ['population','gdpHundredMillionUSD'])if(x[k]!=null&&(!Number.isFinite(x[k])||x[k]<0))throw Error('人口 / GDP 必须为非负数');}
 const countries=new Set(p.countries.map(c=>c.id));for(const c of p.countries){if(c.parentId&&!countries.has(c.parentId))throw Error('属地的上级国家不存在');const seen=new Set([c.id]);let parent=c.parentId;while(parent){if(seen.has(parent))throw Error('国家归属不能形成循环');seen.add(parent);parent=p.countries.find(x=>x.id===parent)?.parentId;}}
 for(const c of p.cities){if(!countries.has(c.countryId)||!Array.isArray(c.coordinates)||c.coordinates.length!==2||!c.coordinates.every(Number.isFinite)||Math.abs(c.coordinates[0])>180||Math.abs(c.coordinates[1])>90)throw Error('城市归属或经纬度无效');}
 const scan=x=>{if(!x||typeof x!=='object')return;for(const [k,v] of Object.entries(x)){if(['media','elevation','elevationSource','customDem'].includes(k))throw Error('精简版不接受配图或高程数据');if(typeof v==='string'&&v.startsWith('data:image/'))throw Error('精简版不接受图片');scan(v);}};scan(p);
 if(p.boundaries){if(p.boundaries.type!=='FeatureCollection'||!Array.isArray(p.boundaries.features))throw Error('疆域数据无效');for(const f of p.boundaries.features){if(!countries.has(f.properties?.id)||!['Polygon','MultiPolygon'].includes(f.geometry?.type))throw Error('疆域与国家不匹配');const polys=f.geometry.type==='Polygon'?[f.geometry.coordinates]:f.geometry.coordinates;for(const poly of polys)for(const ring of poly){if(ring.length<4)throw Error('疆域环未闭合');for(const pt of ring)if(!Array.isArray(pt)||pt.length!==2||!pt.every(Number.isFinite)||Math.abs(pt[0])>180||Math.abs(pt[1])>90)throw Error('疆域坐标无效');if(String(ring[0])!==String(ring.at(-1)))throw Error('疆域环未闭合');}}}
 return p;
}
